/*
* Autogenerated java file: ${definition.name}.java
* Date: ${date}
* Source: ${model.source.fileName}
*/ 

// Package
package ${definition.package}; 

// Imports

// Class

/* 
* Class definition for ${definition.name}
*/
public class ${definition.name} ${extends,optional,definition.superClass} ${definition.superClass,optional} ${implements, optional, definition.interfaces} ${interfaces, optional} {

// Attributes
${iterate, definition.attributes, attribute}
    private ${model.attribute.type} ${model.attribute.name};
${end}
// Methods

${iterate, definition.methods, method}
    private ${model.method.returnType} ${model.method.name} (${model.method.parameters}) {
        
        ${model.method.code}
    }
${end}
}