/*
* Autogenerated java file: {{definition.name}}.java
* @date: {{date}}
* @source: {{model.source.fileName}}
* @copyright: {{copyright}}
*/ 

package {{definition.package.name}}; 

// Imports

/**
* Class definition for {{definition.name}}
*/
public class {{definition.name}} {{#if definition.superClass}}extends {{definition.superClass}}{{/if}} {{#if definition.interfaces}}implements {{definition.interfaces}} {{/if}} {

{{#each definition.attributes as |attribute|}}

    /** {{attribute.name}} */
    private {{attribute.type}} {{attribute.name}};
{{/each}}

{{#each  definition.methods as |method|}}

    /**
     * {{method.name}}
     */
    public {{method.type}} {{method.name}} ({{#each method.parameters as |parameter|}}{{parameter.type}} {{parmeter.name}}{{comma}}{{/each}}) {
        {{method.code}}
    }
{{/each}}
}