/*
* Autogenerated java file: {{definition.name}}.java
* @date: {{date}}
* @source: {{model.source.fileName}}
* @copyright: {{copyright}}
*
* @author: {{author}}
* @uml {{definition.id}}
*/ 

package {{definition.package.name}}; 

// Imports
{{#each definition.imports as |import|}}
    {{import}};
{{/each}}

/**
* Interface definition for {{definition.name}}
*/
public class {{definition.name}}
    {{#if definition.superClass}}extends {{definition.superClass}}{{/if}} {

    {{#each definition.attributes as |attribute|}}{{#if @index}},{{/if}}
     /** {{attribute.name}} 
     * @uml {{attribute.id}}
    */
    {{attribute.name}}{{/each}};
 
{{#each  definition.methods as |method|}}
    /**
     * {{method.name}}
     * 
     * {{#each method.parameters as |parameter|}}
     *  @param {{parameter.name}} {{parameter.type}}
     * {{/each}})
     * @returns {{method.type}} 
     * @uml {{method.id}}
     */
    {{method.type}} {{method.name}} ({{#each method.parameters as |parameter|}}{{#if @index}}, {{/if}}{{parameter.type}} {{parameter.name}}{{/each}}) {
        {{method.code}}
    }
{{/each}}
}