/*
* Autogenerated typescript file: {{definition.name}}.ts
* @date: {{date}}
* @source: {{model.source.fileName}}
* @copyright: {{copyright}}
* @uml {{definition.id}}
*/ 

{{#each definition.imports as |import|}}
import {{import.name}} from '{{import.package}}/{{import.name}}';
{{/each}}

/**
* Interface definition for {{definition.name}}
* @uml {{definition.id}}
*/
export interface {{definition.name}} {{#if definition.superClass}}extends {{definition.superClass}}{{/if}} {

{{#each  definition.methods as |method|}}
    /**
     * {{method.name}}
     * 
     * {{#each method.parameters as |parameter|}}
     *  @param {{parameter.name}} {{parameter.type}}
     * {{/each}})
     * @returns {{method.type}} 
     * @uml {{method.id}}
     */
    {{method.name}} ({{#each method.parameters as |parameter|}}{{#if @index}}, {{/if}}{{parameter.type}} {{parameter.name}}{{/each}}): {{method.returnType}}{
        {{method.code}}
    }
{{/each}}
}