/*
* Autogenerated java file: {{definition.name}}.java
* @date: {{date}}
* @source: {{model.source.fileName}}
* @copyright: {{copyright}}
*/ 

// Package
package {{definition.package.name}}; 

// Imports

/**
* Interface definition for {{definition.name}}
*/
public interface {{definition.name}} {{#if definition.superClass}}extends {{definition.superClass}}{{/if}} {

    // Methods

{{#each  definition.methods as |method|}}
    private {{method.returnType}} {{method.name}} ({{method.parameters}}) {
        {{method.code}}
    }
{{/each}}
}