env:
  browser: true
  es2021: true
extends: standard-with-typescript
overrides: []
parserOptions:
  ecmaVersion: latest
  project: ./tsconfig.json
  sourceType: module
rules: {
  "space-before-function-paren": "always",
  "semi": "off",
  "@typescript-eslint/semi": "off",
  "quotes": "off",
  "@typescript-eslint/quotes": "off"
}
